name: CI Pipeline

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request_target:
    branches: ["main"]

env:
  REGISTRY: docker.io
  DOCKER_ORG: demonstrationorg
  REGISTRY_IMAGE: demonstrationorg/juvenile
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}
  DOCKERFILE_PATH: Dockerfile
  COMPARE_TAG: latest
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
      pull-requests: write
    strategy:
      matrix:
        platform:
          - linux/amd64

    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV   
      
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.SHA }}
        
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log into registry
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          labels: |
            org.opencontainers.image.revision=${{ env.SHA }}
            com.docker.image.source.entrypoint=${{ env.DOCKERFILE_PATH }}
        
      - name: Build and push Docker by digest
        id: build
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
          sbom: true
          provenance: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"          
      
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

      - name: Build and push Docker image on PR
        id: build-and-push-pr
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: "linux/arm64"
          sbom: false
          provenance: false 
          github-token: ${{ secrets.GH_TOKEN }} # to be able to write the comment